user:
  name: Aquiles
  last_name: Carattino

daq:
  port: '/dev/ttyACM0'
  resistance: 220ohm
  minimum_out: 0V
  maximum_out: 3.3V

scan:
  start: 0V
  stop: 3.3V
  step: 0.1V
  delay: 100ms
  channel_in: 0
  channel_out: 0

saving:
  filename: 'IV_Curve.dat'
  directory: '/home/aquiles/Data'

